on:
  workflow_run:
    workflows: [ci]
    branches-ignore: [main]
    types: 
      - completed


jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ github }}"
      - run: echo "${{ github.event.workflow_run.conclusion }}"
      - run: echo "${{ github.actor }}"
      - run: echo "${{ github.event_name }}"
      - run: echo "${{ github.event.pull_request.draft }}"
      - run: echo "${{ github.event.action }}"
      
