on:
  workflow_run:
    workflows: [ci]
    branches-ignore: [main]
    types: 
      - completed


jobs:
  on-success:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ JSON.stringify(github) }}"
      
